apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: promo-test
  janus-idp.io/tekton: promo-test
  backstage.io/kubernetes-id: promo-test
  backstage.io/kubernetes-namespace: rhtap 
  app.kubernetes.io/part-of: promo-test
resources: 
- deployment.yaml
- route.yaml
- service.yaml
