apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
  name: do-promotion 
spec: 
  params:
    - description: Gitops Repo Url 
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string 
    - description: If push update the deployment, if PR, only run checks.
      name: event-type
      type: string 
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision) 
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: handle-promote-action
      params:
        - name: gitops-repo-url
          value: $(params.git-url)  
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: handle-promote-action
      workspaces:
        - name: output
          workspace: workspace  