apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: handle-promote-action
spec:
  description: Task to promote between environments.
  params:
    - name: gitops-repo-url
      type: string
      description: URL of gitops repository to update with the newly built image.
    - name: gitops-auth-secret-name
      type: string
      default: gitops-auth-secret
      description: |
        Secret of basic-auth type containing credentials to commit into gitops repository.
  workspaces:
  - description: The git repo will be cloned onto the volume backing this Workspace.
    name: output
  volumes:
    - name: gitops-auth-secret
      secret:
        secretName: $(params.gitops-auth-secret-name)
        optional: true
  steps:
  - name: extract-actions 
    image: quay.io/redhat-appstudio/appstudio-utils:d8a93bf5650424a4f20ee065578609792d70af1c
    script: |
      #!/bin/bash   
      COMPONENT_NAME=$(yq .metadata.name /workspace/output/source/application.yaml) 
      # be sure not to modify the source repo that was cloned  
      echo "COMPONENT_NAME=$COMPONENT_NAME" >/workspace/output/handle-promote-action.env
      cat /workspace/output/handle-promote-action.env
  - name: promotion-step
    image: quay.io/redhat-appstudio/task-toolset@sha256:931a9f7886586391ccb38d33fd15a47eb03568f9b19512b0a57a56384fa52a3c
    volumeMounts:
      - name: gitops-auth-secret
        mountPath: /gitops-auth-secret
    env:
      - name: PARAM_GITOPS_REPO_URL
        value: $(params.gitops-repo-url) 
    script: |
      if test -f /gitops-auth-secret/password ; then
        gitops_repo_url=${PARAM_GITOPS_REPO_URL}
        remote_without_protocol=${gitops_repo_url#'https://'}

        password=$(cat /gitops-auth-secret/password)
        if test -f /gitops-auth-secret/username ; then
          username=$(cat /gitops-auth-secret/username)
          echo "https://${username}:${password})@${hostname}" > "${HOME}/.git-credentials"
          origin_with_auth=https://${username}:${password}@${remote_without_protocol}.git
        else
          origin_with_auth=https://${password}@${remote_without_protocol}.git
        fi
      else
        echo "git credentials to push into gitops repository ${PARAM_GITOPS_REPO_URL} is not configured."
        echo "gitops repository is not updated automatically."
        echo "You can update gitops repository with the new image: ${PARAM_IMAGE} manually"
        echo "TODO: configure git credentials to update gitops repository."
        exit 0
      fi 
      cd /workspace/output/source 
      if test -f promotion-action ; then
        ACTION=$(cat promotion-action) 
        source /workspace/output/handle-promote-action.env 
        echo "Repo = $PARAM_GITOPS_REPO_URL"
        echo "COMPONENT_NAME=$COMPONENT_NAME"  
        echo "ACTION=$ACTION" 
        case $ACTION in 
          "promote-dev-stage")
            SRC_OVERLAY=development
            DST_OVERLAY=stage
            ;;
            
          "promote-stage-prod")
            SRC_OVERLAY=development
            DST_OVERLAY=stage
            ;; 

          *)
            echo "Invalid promptions action $ACTION"
            exit 0
            ;;
        esac 
 
        SRC_PATCH="components/${COMPONENT_NAME}/overlays/$SRC_OVERLAY/deployment-patch.yaml"
        DST_PATCH="components/${COMPONENT_NAME}/overlays/$DST_OVERLAY/deployment-patch.yaml"
        
        
        git config --global user.email "rhtap@noreplay.com"
        git config --global user.name "promotion-automation-handler" 
        rm -rf promotion-action

        git status
        echo "Promoted ${SRC_OVERLAY} to: ${DST_OVERLAY}"
        cp $SRC_PATCH $DST_PATCH  
        git diff -U0
        git status

        # git clone ${PARAM_GITOPS_REPO_URL}
        # cd ${gitops_repo_name} 
        
        git add .
        git commit -m "Promoted ${SRC_OVERLAY} to: ${DST_OVERLAY}"
        git remote set-url origin $origin_with_auth
        git push
      else 
        echo "No action for promotion found."
      fi