apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promo-test-on-push 
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]" 
    pipelinesascode.tekton.dev/pipeline: ".tekton/do-promotion.yaml"
    pipelinesascode.tekton.dev/task-0: ".tekton/handle-promote-action.yaml" 
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/git-clone.yaml"
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'   
  - name: revision
    value: '{{revision}}'   
  - name: target-branch
    value: '{{target_branch}}'    
  - name: commit-message
    value: '{{body.head_commit.message}}'   
  pipelineRef:
    name: do-promotion 
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
